# Utilisation d'une image Python officielle
FROM python:3.9-slim

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers dans le conteneur
COPY requirements.txt requirements.txt
COPY ✨_Welcome.py ✨_Welcome.py
COPY data/movies.json data.json
COPY data/movies.films.csv data.csv

# Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Commande exécutée au démarrage du conteneur
# CMD ["python", "main.py"]
CMD ["streamlit", "run", "✨_Welcome.py"]